module.exports = {
  up: (queryInterface) => queryInterface.bulkInsert('Looks', [
    {
      id: 0,
      chasis_compatible: "WBALM1567",
      nombre: "Llanta BMW Blackout set x4",
      categoria: "Llanta",
      precio: 1200000,
      createdAt: new Date(),
      updatedAt: new Date(),
      },
      {
      id: 1,
      chasis_compatible: "WBALM1567",
      nombre: "neumatico michelin set x4",
      categoria: "Neumatico",
      precio: 600000,
      createdAt: new Date(),
      updatedAt: new Date(),
      },
      {
      id: 2,
      chasis_compatible: "WBALM1567",
      nombre: "neumatico dunlop set x4",
      categoria: "Neumatico",
      precio: 400000,
      createdAt: new Date(),
      updatedAt: new Date(),
      },
      {
      id: 3,
      chasis_compatible: "WBALM1567",
      nombre: "capot fibra de carbono",
      categoria: "Capot",
      precio: 800000,
      createdAt: new Date(),
      updatedAt: new Date(),
      }, 
      {
        id: 4,
        chasis_compatible: "WBALM1567",
        nombre: "Llanta Voosen Tecnik set x4",
        categoria: "Llanta",
        precio: 1400000,
        createdAt: new Date(),
        updatedAt: new Date(),
        },
        {
          id: 5,
          chasis_compatible: "WBALM1567",
          nombre: "Capot Aluminio tomas de aire",
          categoria: "Capot",
          precio: 400000,
          createdAt: new Date(),
          updatedAt: new Date(),
          },
  ]),
  down: (queryInterface) => queryInterface.bulkDelete('Looks', null, {}),
};
